### ISSUE TITLE
Display title (if possible) and link of currently playing song in Web client

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#120]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be nice to display the name of the song that is currently playing (when possible) and the link used for it.

It is difficult to find out what song is playing when just using `/audio` together with speakers as you (obviously) hear the music, but it may not always be clear what the name of it is.

So having this displayed could help reduce the number of players, that constantly ask "What is that song's name?"

This could/should be an option in the config too, to hide this information in case you might not wanna display it.

**Describe alternatives you've considered**
The only alternative would be to mention the song name and link somewhere like a sign or hologram or similar which isn't always optimal.

**Additional context**

**Comment by Mindgamesnl** [comment]
Problem with this is that we (as OpenAudioMc) don't have the required data to display, and even if there are ID3 tags, those will be loaded clientside and browser support for that is scarce, if at all.

Adding it to a config file as per-media meta is really poor for user experience since it's an advertised feature but an absolute hell to manage and write. If you have another idea on how to accomplish this, I'd like to hear from you.

If, however, you already have this data for yourself, feel free to write an addon using our Cards API
![card code](https://user-images.githubusercontent.com/10709682/72610958-195a1d80-3929-11ea-82b3-396d73c38868.jpeg)
![card example](https://user-images.githubusercontent.com/10709682/72610966-1fe89500-3929-11ea-9dd0-edda1a52079e.png)

I personally don't think many users will use it (as in openaudiomc users, not players from servers) and therefor don't think its worth the confusion.

**Comment by Andre601** [comment]
I'm not that well known with web stuff so I wasn't aware that there isn't an (easy) way to retrieve and display the title...

Would it at least be a possibility to display the link itself? Since you define a link for the speaker or in the `/audio` command would it make sense that this could be sent through the data in the link to connect with the audio client.

**Comment by Mindgamesnl** [comment]
Also no, since the source send to the client doesn't have to be the one you entered

- In the case of an mp3 link, it is the direct file
- in the case of youtube, coundcloud, drive or dropbox it gets turned into a direct file by one of our cdn's so the browser can play it

In every scenario, it is the direct file available to download and still not giving the user _any_ details on information, instead, it'll make is more like a distribution platform which leads to some gray area we don't want to enter.

**Comment by Andre601** [comment]
Understandable. Thanks for the clarification.
