### ISSUE TITLE
Help Wanted: Safari Compatibility

### ISSUE THREAD

**Issue by awesomepandapig** [Mindgamesnl/OpenAudioMc#133]
**Describe the bug**
I am unable to hear audio through Safari on Mac OS. I have tried using Chrome and Firefox and both are able to play audio. Also the speaker icon which should appear in the address bar to indicate that audio is playing is absent.

**To Reproduce**
1. Enter "/audio"
2. Click on the message in the chat and paste the link in Safari
3. Connect to the audio client
4. Play music through open audio

**Expected behavior**
Music should be audible and a speaker icon should appear in the address bar indicating that it is playing audio.

**Screenshots**
What I see
<img width="591" alt="Screen Shot 2020-04-29 at 1 51 29 AM" src="https://user-images.githubusercontent.com/34806109/80577786-54ee9400-89bc-11ea-8502-577002251906.png">
What I should see
<img width="654" alt="Screen Shot 2020-04-29 at 1 48 21 AM" src="https://user-images.githubusercontent.com/34806109/80577811-6172ec80-89bc-11ea-91d7-365a605b5454.png">

**Desktop:**
 - Mac OS Catalina 10.15.4
 - Safari 13.1
 - Vanilla Minecraft 1.15.2

**Comment by Mindgamesnl** [comment]
Does it connect properly?

**Comment by awesomepandapig** [comment]
Yes it shows me my player icon and says "connected to audio client"

**Comment by Mindgamesnl** [comment]
Odd, on it.

**Comment by Mindgamesnl** [comment]
Basically, what i found thus far

- Media is loaded propperly
- Media ready events fire
- Play method gets called
- Music never plays and the promise never gets accepted nor denied

**Comment by SnowBlinderP** [comment]
> * Play method gets called
> * Music never plays and the promise never gets accepted nor denied

Apple ™

**Comment by Mindgamesnl** [comment]
Ok, depressing news.
Turns out that there's nothing to be done about it.

You *can* allow autoplay for a site, but it still gets blocked in the background, there's no way to get around it.

Closing the issue for now and will add a warning for safari users, if someone finds a way to do it, please re-open this issue.

**Comment by Mindgamesnl** [comment]
![image](https://user-images.githubusercontent.com/10709682/83063067-df7bef00-a05f-11ea-9790-c9fa535fd119.png)
Safari users now get kicked to this page.

**Comment by stijnb1234** [comment]
https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

Maybe change Safari to Safari on MacOS. On iPhone and ipad it works fine. And I know that most of the users won't use it on a mobile device, but now it's not clear what is meant with Safari.

**Comment by Mindgamesnl** [comment]
> Maybe change Safari to Safari on MacOS. On iPhone and ipad it works fine. And I know that most of the users won't use it on a mobile device, but now it's not clear what is meant with Safari.

I don't consider mobile a supported platform due to poor content loading on most (if not all) mobile browsers and because they pose even more restrictions to background processes when in other apps and throttles or even blocks network entirely, so mentioning safari on mobile to work would endorse mobile usage.
