### ISSUE TITLE
Server peaks in 30 seconds

### ISSUE THREAD

**Issue by Blueeyestar** [Mindgamesnl/OpenAudioMc#140]
Paper:Paper version git-Paper-349 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT

Openaudiomc-Version: 6.3

we have noticed that our server gets a peak performance every 30 seconds.
after a long search we found out that it was openaudiomc.
This means that we always have a loss of 1-3% TPS loss.

![audio](https://user-images.githubusercontent.com/35557302/84478986-7c5e9f00-ac92-11ea-95c2-cd0480613e8d.png)

As soon as we remove Openaudio the server stabilizes and shows no more peaks.

![audio2](https://user-images.githubusercontent.com/35557302/84479083-a021e500-ac92-11ea-8e9c-ff7b61c2d48d.png)

We also have a timing:
https://timings.aikar.co/?id=c6254f9071064f8f92cf652a4879dc66

OpenAudioMc::Task: com.craftmend.openaudiomc.spigot.modules.speakers.tasks.SpeakerGarbageCollection (interval:600)
count(40)  total(28.04% 4.459s, 90.08% of tick)

**Comment by Mindgamesnl** [comment]
On it!
May I ask how many speakers you have in your world? (can be read out through `/oa state`, or `/openaudiomc:oa state` if you are running bungee)

**Comment by Mindgamesnl** [comment]
Nevermind, already just resolved it in https://github.com/Mindgamesnl/OpenAudioMc/commit/6fdff7df7018fd5ca00eff4ecb7a8bd780c15532 to be released with the next update.

The first run will still be as heavy as it is, but it'll do them in phases and not reiterate over speakers that have already been validated and even out in 2+- minutes after the server started. This just has to be done in the main thread (unfortunately) because of concurrency issues with the Minecraft world and bukkit API restrictions.

**Comment by Blueeyestar** [comment]
do you already know what the plugin comes out? or do you wait until 1.16 comes out?
