### ISSUE TITLE
Https default and http fallback

### ISSUE THREAD

**Issue by Xetaxheb** [Mindgamesnl/OpenAudioMc#157]
**Is your feature request related to a problem? Please describe.**
Trying to play a url without https/http fails

**Describe the solution you'd like**
It would be nice if, perhaps on otherwise erroring, an attempt was made to prefix the url with https:// and then http://

**Additional context**
Attempt playing soundcloud.com/takka-music/harambae and it will fail but https://soundcloud.com/takka-music/harambae and http://soundcloud.com/takka-music/harambae both work fine.

**Comment by Mindgamesnl** [comment]
Closed, this would break local resources on custom clients.

**Comment by Xetaxheb** [comment]
Why would this not be an option to fallback to if the resource would _otherwise_ error? Could it be a server or client config option instead then?

And is the use-case of "custom clients" so much more expected than a web link for the majority of your userbase that it wouldn't mandate a _file://_ or _local://_ or _resource://_ or _./_ or etc... over mandating _https://_ or _http://_ ?

I'll be honest, i'm not really sure what you mean by "custom clients" though because that is vague enough to mean a wide range of things. All i'm aware of about openaudiomc is it's a plugin that will run serverside on spigot-capable servers and the web interface.

**Comment by Mindgamesnl** [comment]
I meant that there are plenty of users who use a custom client, by which I mean one on their own web server and it's common for them to add resources on the same web server, so referring to `sounds/hello.mp3` will automatically point to `https://myclient.example.com/sounds/hello.mp3`

However, as you said, there _could_ be the option to enable this feature itself but I don't see why that would be useful in a real scenario other than adding more complexity, I don't see in what case you would have a full url to the sound, but aren't able to prefix it yourself with `http(s)://`, you could do it yourself using the url mutation API but I don't see it being added as a native feature.

_(as a final note, I didn't mean to point to `file://` or any real local resources at all, it isn't even possible to load files from the client without user interaction or them being manually selected first because of privacy reasons)_
