### ISSUE TITLE
Velocity Plugin

### ISSUE THREAD

**Issue by fluse1367** [Mindgamesnl/OpenAudioMc#161]
So i think a [Velocity](https://velocitypowered.com/) Plugin would really come in handy for ppl who dont use Bungeecord.

**Comment by Mindgamesnl** [comment]
Perhaps if more people would find a use for it, don't have a lot of time at the moment and figure that it's better spent implementing new features of improving the backend instead of spreading to another proxy entirely, feel free to shoot in a merge request or check in the discord (feedback channel) if you can get more people to request it.
I'll close the issue for now since I see no reason to invest time in it at the moment.
