### ISSUE TITLE
Website: Audio visualization

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#166]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be nice, if the Website could offer some audio visualization (SFZ visualization) to also "see" the music in it.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Mindgamesnl** [comment]
Sadly not feasible, we default to HTML audio which can't be processed.
3D speakers are the only exception, since they get balancing nodes, but that also means that those speakers use our proxy to serve user content to circumvent chromes weird inconsistent cors policies with media.
Doing this for every request would get too expensive and add latency for every type of audio.
