### ISSUE TITLE
Why don't you use the Maven dependency system?

### ISSUE THREAD

**Issue by games647** [Mindgamesnl/OpenAudioMc#34]
I see that you use Maven, but why do you put so much dependency code into your source folder if there is a Maven dependency available for it. 

Then you don't need to put the source files of that projects there and dependencies will be downloaded automatically once you change the version line in the pom.xml.

**Comment by Mindgamesnl** [comment]
If you mean the okio, okhttp and socket.io

I use a standard socket.io libary which depends on okhttp which in turn depends on okio.

The problem is that they where designed with android in mind and so won't work in spigot (andriod function call's etc)

**Comment by games647** [comment]
I mean this https://github.com/Mindgamesnl/OpenAudioMc/tree/master/Plugin%20source%20code/src/okio

It looks like you just copied the contents from https://github.com/square/okio/tree/master/okio/src/main/java/okio into your source folder

**Comment by Mindgamesnl** [comment]
I know what you mean and yes the socketio and ok* are from there, what i mean is it was constantly screeming android class not found errors while testing with the maven version.

After playing with it for a night i tested copying it to the source but manualy removing all the referenses to android (since the stack trace) and this resolved the issue.

**Comment by games647** [comment]
I have no idea what you tried, but I removed the packages
* okhttp3
* io.socket
* okio

and replaced them in Maven and it's working fine. I could connect to over with /connect and hear the music. The only thing I had to fix was a NPE for connecting to the server on join.
