### ISSUE TITLE
Playlist, speaker and region ownership

### ISSUE THREAD

**Issue by mbentity** [Mindgamesnl/OpenAudioMc#421]
It would be lovely if users could create and modify their own speakers and playlists, and attach playlists to their own worldguard regions, without being able to modify other users' playlists, regions and speakers.

This would open up the plugin to more user-based possibilities, instead of reserving it for admin work, allowing all users to enhance their own cities and bases with custom music.

**Comment by Mindgamesnl** [comment]
I'm hesitant to add this for a couple of different reasons, most of them boiling down to security.
Media is loaded by the web client, in most cases without a proxy. This is okay because the server sending the media is considered a trusted source, where only people with explicit permission can add media or force it to load. Allowing anyone to add media would open the door to IP loggers or other malicious links being used. I don't think it's something that'll be implemented in the main plugin releases unless there's a viable workaround.

**Comment by mbentity** [comment]
I see, the concerns make a lot of sense.
I was thinking about some kind of setting that allowed server owners to whitelist domains you can link tracks from, but that would probably bloat the plugin and be better suited for an external addon, since as far as I understand that is not the main goal of the core plugin.
